services:
  postgres:
    image: pgvector/pgvector:pg17

    container_name: pgvector-db

    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: