spring.application.name=evaluate.ai

spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.0-flash

spring.ai.google.genai.embedding.api-key=${GOOGLE_GENAI_API_KEY}


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=spring-ai
spring.datasource.username=postgres
spring.datasource.password=manoj@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

